name: subs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Basic
  - python=3.10
  - pytorch-cuda==12.4
  - pytorch==2.4.1
  - ffmpeg
  # Tools
  - ipykernel
  - matplotlib
  - tqdm
  # CN_TRA -> CN_SIMP
  - torchvision
  - torchaudio
  - easyocr
  # EN -> CN_SIMP
  - transformers
  - accelerate
  - pip
  - pip:
    - srt
    - zhconv
    #- vllm