name: subs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Basic
  - python=3.10
  - pytorch=2.2.*=*cuda*
  - ffmpeg
  # Tools
  - ipykernel
  - matplotlib
  - tqdm
  # CN_TRA -> CN_SIMP
  - torchvision
  - torchaudio
  - easyocr
  - pip
  - pip:
    - zhconv